---
  - name: make sure sendmail is removed
    package:
      name: sendmail
      state: absent
    become: yes
    tags:
       - build_ami

  - name: Update cache and upgrade all installed packages to latest
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: safe
    become: yes
    tags:
      - build_ami

  - name: add gateway client pub key to ubuntu user authorized_keys file
    authorized_key:
      key: "{{ client_pub_key }}"
      user: "{{ ansible_user }}"
    become: yes

  - name: install openvpn
    package:
      name: openvpn
      state: latest
    become: yes
    tags:
       - build_ami

  - name: install iptables-persistent
    package:
      name: iptables-persistent
      state: latest
    become: yes
    tags:
       - build_ami

  - name: copy sysctl config
    copy:
      src: sysctl-config
      dest: /etc/sysctl.conf
    become: yes
    tags:
       - build_ami

  - name: reload sysctl
    command: sysctl -p
    become: yes
    tags:
       - build_ami

  - name: reload sysctl
    command: sysctl --system
    become: yes
    tags:
       - build_ami

  - name: copy openvpn server config
    copy:
      src: openvpn-config
      dest: /etc/openvpn/server.conf
      mode: 0600
    become: yes
    tags:
       - build_ami

  - name: copy iptables config
    copy:
      src: iptables-config
      dest: /etc/iptables/rules.v4
    become: yes
    tags:
       - build_ami

  - name: add openvpn static key to server
    copy:
      content: "{{ openvpn_static_key }}"
      dest: /etc/openvpn/static.key
      mode: 0600
    become: yes
    tags:
       - provision_gateway

  - name: start openvpn service
    service:
      name: openvpn
      state: restarted
      enabled: yes
    become: yes
    tags:
       - provision_gateway

  - name: restart iptables-persistent
    service:
      name: iptables-persistent
      enabled: yes
      state: restarted
    become: yes
    tags:
       - build_ami
